### ISSUE TITLE
Request for thrall wipe/cleaning

### ISSUE THREAD

**Issue by Wrexthor** [A15Bog/conanexilessql#2]
Seeing as thralls make server restarts take 10 minutes or more, if possible some kind of thrall wipe or cleaning would be greatly appreciated!

**Comment by gabrielbuzziv** [comment]
Remove players trall to fast restart?

**Comment by Wrexthor** [comment]
Also have some rather huge issues with lag even with 1 player online and i think it might have to do with thralls, or at least worth investigating if it does.

**Comment by gabrielbuzziv** [comment]
I believe its possible, since you can get the position of each player.
I'm developing a tool to manage all this things based in this repo, i added some features like: 

- Current Online Player
- Visual map with online players Locations
- Heal buildings from a specific owner
- Delete building from specific owner
- Rename characters
- Delete a guild (remove all structures from the server)
- Remove build from players or guilds that at least 1 player didn't connect in the last week (this is custom, can be managed)
- Decay system (the same of this repo)
- Clear player inventory

And i will add in the next days
- Visual map showing where is the base of each owner (this way i can find irregular builds in my server)

I hope i publish this to community in the next week.

The only requirement will be the server allows you to install PHP

**Comment by Wrexthor** [comment]
That sounds incredibly useful, looking forward to it, a lot!

**Comment by gabrielbuzziv** [comment]
![preview](http://i.imgur.com/4pfG4S4.png)

**Comment by A15Bog** [comment]
I updated the scripts today and they are in use on the #3 server on topconanservers.com, A15. The previous scripts were not 100%. The full version of decay along with the delete has also been added.
